### ISSUE TITLE
Crash if TestBrowser is displayed when VS is loaded

### ISSUE THREAD

**Issue by HellBrick** [HellBrick/TestBrowser#43]

**Comment by HellBrick** [comment]
```
  <entry>
    <record>694</record>
    <time>2015/11/02 12:50:11.813</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [TestBrowserPackage]</description>
    <guid>{70CB3239-BDE6-4A23-9C90-8D355765613B}</guid>
  </entry>
  <entry>
    <record>695</record>
    <time>2015/11/02 12:50:11.853</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
    <description>Assembly timestamp in MEF Cache does not match loaded assembly timestamp</description>
    <path>Microsoft.VisualStudio.TestWindow.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; code-base: file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 14.0/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Microsoft.VisualStudio.TestWindow.Core.dll</path>
  </entry>
  <entry>
    <record>696</record>
    <time>2015/11/02 12:50:11.855</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [TestBrowserPackage]</description>
    <guid>{70CB3239-BDE6-4A23-9C90-8D355765613B}</guid>
    <hr>80131500</hr>
    <errorinfo>The Visual Studio component cache is out of date. Please restart Visual Studio.</errorinfo>
  </entry>
  <entry>
    <record>697</record>
    <time>2015/11/02 12:50:11.855</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [TestBrowserPackage]</description>
    <guid>{70CB3239-BDE6-4A23-9C90-8D355765613B}</guid>
    <hr>80131500</hr>
    <errorinfo>The Visual Studio component cache is out of date. Please restart Visual Studio.</errorinfo>
  </entry>
```

**Comment by HellBrick** [comment]
```
  <entry>
    <record>481</record>
    <time>2015/11/02 13:01:55.959</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [TestBrowserPackage]</description>
    <guid>{70CB3239-BDE6-4A23-9C90-8D355765613B}</guid>
  </entry>
  <entry>
    <record>482</record>
    <time>2015/11/02 13:01:55.975</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
    <description>Assembly timestamp in MEF Cache does not match loaded assembly timestamp</description>
    <path>Microsoft.VisualStudio.TestWindow.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; code-base: file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 14.0/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Microsoft.VisualStudio.TestWindow.Core.dll</path>
  </entry>
  <entry>
    <record>483</record>
    <time>2015/11/02 13:01:55.975</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [TestBrowserPackage]</description>
    <guid>{70CB3239-BDE6-4A23-9C90-8D355765613B}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo>Object reference not set to an instance of an object.</errorinfo>
  </entry>
  <entry>
    <record>484</record>
    <time>2015/11/02 13:01:55.975</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [TestBrowserPackage]</description>
    <guid>{70CB3239-BDE6-4A23-9C90-8D355765613B}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo>Object reference not set to an instance of an object.</errorinfo>
  </entry>
  <entry>
    <record>485</record>
    <time>2015/11/02 13:02:01.477</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Construction of frame content failed.&#x000D;&#x000A;Frame identifier: ST:0:0:{2cf8fca7-b42d-4640-828c-c13246d59e9c}&#x000D;&#x000A;Frame caption: Test Browser&#x000D;&#x000A;Exception details:&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid&amp; packageGuid, Int32 reason, Guid&amp; context)&#x000D;&#x000A;   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()&#x000D;&#x000A;   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()</description>
  </entry>
```

**Comment by HellBrick** [comment]
```
Microsoft.VisualStudio.ExtensibilityHosting.InvalidMEFCacheException: The Visual Studio component cache is out of date. Please restart Visual Studio.
   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.<LoadAssembly>b__12_0(AssemblyName assemblyNameParam)
   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.SafeGetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 valueFactory)
   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.GetManifest(Resolver resolver, AssemblyName assemblyName)
   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.get_ResolvedType()
   at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_ImportingSiteType()
   at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_ImportingSiteTypeWithoutCollection()
   at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_IsLazy()
   at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_LazyFactory()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.Cast(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToSingleImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.SatisfyImportsOnce(ComposablePart part)
   at Microsoft.VisualStudio.Composition.NetFxAdapters.CompositionService.SatisfyImportsOnce(ComposablePart part)
   at HellBrick.TestBrowser.TestBrowserPackage.InitializeServiceContext()
   at HellBrick.TestBrowser.TestBrowserPackage.Initialize()
```
